/*
 * Muhammad Faisal Amir
 * id.amirisback.bandung
 * Copyright 2017
 */
package promadika.petugas;

import promadika.Index;
import promadika.connection;
import promadika.function;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JPanel;

import java.io.File;
import java.io.FileInputStream;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Blob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.FileImageInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Faisal Amir
 */
public class Petugas_Edit extends javax.swing.JFrame {
    connection conn = new connection();
    function func = new function();
    Petugas_List data = new Petugas_List();
    private Object get_id_petugas;
    private String sql = "";
    private String path_file, nama_file, nama_foto, nama, kua_cabang, path_save_foto, nama_foto_fromDb;
    private int lebar, tinggi, ukuran;
    private File foto;
    private FileInputStream inputFoto;
    Blob foto_db;

    
    /**
     * Creates new form Petugas
     */
    public Petugas_Edit(Object get_id_petugas) {
        initComponents();
        conn.ConnectToDB();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.get_id_petugas = get_id_petugas;
        showData();
    }

    private Petugas_Edit() {
    }
   
    public boolean isEmpty(){
        return 
                txt_nama_petugas.getText().equals("") || 
                txt_kua_cabang.getText().equals("");
    }
    
    public void resizeImage(){
        try {
            BufferedImage imgUkuranAsli = ImageIO.read(foto);
            lebar = panel_foto.getWidth();
            tinggi = panel_foto.getHeight();
            BufferedImage imgResize = new BufferedImage(lebar, tinggi, BufferedImage.TYPE_INT_ARGB);
            Graphics2D imgTampil = imgResize.createGraphics();
            imgTampil.drawImage(imgUkuranAsli, 0, 0, lebar, tinggi, null);
            imgTampil.dispose();
            ImageIcon ImgOut = new ImageIcon(imgResize);
            foto_petugas.setText("");
            foto_petugas.setIcon(ImgOut);
        } catch (Exception e) {
            System.out.println(e);
        }   
    }
    
    public void showData(){
        try {
            sql = "Select * from data_petugas where id_petugas = '"+get_id_petugas+"'";
            conn.setStatement(conn.getConnect().createStatement());
            conn.setResultSet(conn.getStatement().executeQuery(sql));
            while(conn.getResultSet().next()){
                txt_nip_petugas.setText(conn.getResultSet().getString("id_petugas"));
                txt_nama_petugas.setText(conn.getResultSet().getString("nama_petugas"));
                txt_kua_cabang.setText(conn.getResultSet().getString("tempat_kua"));
                nama_foto_fromDb = conn.getResultSet().getString("foto");
                path_save_foto = conn.getFolder_Foto_Petugas()+"/"+nama_foto_fromDb;
                foto = new File(path_save_foto);
                resizeImage();
                txt_nama_foto.setText(nama_foto_fromDb);
            }
        } catch (SQLException e) {
        }
    }
    
    public void saveFotoPetugas(){
        try {
            BufferedImage save = ImageIO.read(foto);
            ImageIO.write(save, "jpg", new File(path_save_foto));
        } catch (IOException e) {
            System.out.println(e);
        }
    }
    
    private void Clear(){
        txt_nama_petugas.setText("");
        txt_kua_cabang.setText("");
        txt_nama_foto.setText("");
        foto_petugas.setText("Foto 3x4");
        foto_petugas.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        H_Petugas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_daftar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hover_daftar = new javax.swing.JLabel();
        panel_tambah = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hover_tambah = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_show_mesg = new javax.swing.JTextField();
        btn_edit_petugas = new javax.swing.JButton();
        str_tambah_data = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_nama_petugas = new javax.swing.JTextField();
        txt_kua_cabang = new javax.swing.JTextField();
        txt_nip_petugas = new javax.swing.JLabel();
        btn_upload = new javax.swing.JButton();
        txt_nama_foto = new javax.swing.JLabel();
        panel_foto = new javax.swing.JPanel();
        foto_petugas = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROMADIKA - Program Informasi Pendataan Data Nikah");
        setSize(new java.awt.Dimension(1343, 674));

        H_Petugas.setBackground(new java.awt.Color(46, 125, 50));
        H_Petugas.setPreferredSize(new java.awt.Dimension(1024, 768));

        jPanel2.setBackground(new java.awt.Color(165, 214, 167));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconProperties/header.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(27, 94, 32));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(102, 187, 106));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconProperties/Petugas_miniIcon.png"))); // NOI18N

        panel_daftar.setBackground(new java.awt.Color(232, 245, 233));
        panel_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_daftarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_daftarMouseEntered(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconProperties/icons8_Contacts_25px.png"))); // NOI18N

        hover_daftar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hover_daftar.setText("Daftar Petugas");
        hover_daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hover_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hover_daftarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_daftarLayout = new javax.swing.GroupLayout(panel_daftar);
        panel_daftar.setLayout(panel_daftarLayout);
        panel_daftarLayout.setHorizontalGroup(
            panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_daftarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(hover_daftar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_daftarLayout.setVerticalGroup(
            panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_daftarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_daftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hover_daftar)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_tambah.setBackground(new java.awt.Color(165, 214, 167));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconProperties/icons8_Plus_25px.png"))); // NOI18N

        hover_tambah.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hover_tambah.setText("Tambah Petugas");
        hover_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hover_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hover_tambahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_tambahLayout = new javax.swing.GroupLayout(panel_tambah);
        panel_tambah.setLayout(panel_tambahLayout);
        panel_tambahLayout.setHorizontalGroup(
            panel_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tambahLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(hover_tambah)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        panel_tambahLayout.setVerticalGroup(
            panel_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(hover_tambah)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(165, 214, 167));
        jPanel8.setPreferredSize(new java.awt.Dimension(171, 47));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Menu Pilihan");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconProperties/icons8_Menu_2_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_daftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_tambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(52, 52, 52))
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(panel_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Copyright - Promadika 2017  ||  Telkom University");

        jLabel10.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("______________________________________________________________________________________________________________________________________________________________________");

        txt_show_mesg.setBackground(new java.awt.Color(46, 125, 50));
        txt_show_mesg.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_show_mesg.setForeground(new java.awt.Color(255, 255, 255));
        txt_show_mesg.setBorder(null);

        btn_edit_petugas.setBackground(new java.awt.Color(0, 102, 102));
        btn_edit_petugas.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btn_edit_petugas.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_petugas.setText("UBAH DATA PETUGAS");
        btn_edit_petugas.setPreferredSize(new java.awt.Dimension(201, 27));
        btn_edit_petugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_petugasActionPerformed(evt);
            }
        });

        str_tambah_data.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        str_tambah_data.setForeground(new java.awt.Color(255, 255, 255));
        str_tambah_data.setText("Ubah Data Petugas");
        str_tambah_data.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel7.setBackground(new java.awt.Color(200, 230, 201));

        jLabel9.setFont(new java.awt.Font("Arial", 3, 15)); // NOI18N
        jLabel9.setText("NIP Petugas    :");

        jLabel11.setFont(new java.awt.Font("Arial", 3, 15)); // NOI18N
        jLabel11.setText("Nama Petugas    :");

        jLabel12.setFont(new java.awt.Font("Arial", 3, 15)); // NOI18N
        jLabel12.setText("KUA Cabang    :");

        txt_nama_petugas.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txt_nama_petugas.setMargin(new java.awt.Insets(5, 10, 10, 5));

        txt_kua_cabang.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txt_kua_cabang.setMargin(new java.awt.Insets(5, 10, 10, 5));

        txt_nip_petugas.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btn_upload.setText("Upload Foto");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        panel_foto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
        panel_foto.setPreferredSize(new java.awt.Dimension(170, 220));

        foto_petugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foto_petugas.setText("Foto 3x4");

        javax.swing.GroupLayout panel_fotoLayout = new javax.swing.GroupLayout(panel_foto);
        panel_foto.setLayout(panel_fotoLayout);
        panel_fotoLayout.setHorizontalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );
        panel_fotoLayout.setVerticalGroup(
            panel_fotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(foto_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_upload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nama_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_nama_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addComponent(txt_kua_cabang, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                        .addComponent(txt_nip_petugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nip_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_nama_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kua_cabang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_upload)
                    .addComponent(txt_nama_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout H_PetugasLayout = new javax.swing.GroupLayout(H_Petugas);
        H_Petugas.setLayout(H_PetugasLayout);
        H_PetugasLayout.setHorizontalGroup(
            H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(H_PetugasLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, H_PetugasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(H_PetugasLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(str_tambah_data))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(H_PetugasLayout.createSequentialGroup()
                                .addComponent(btn_edit_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_show_mesg, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))
                    .addGroup(H_PetugasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(H_PetugasLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        H_PetugasLayout.setVerticalGroup(
            H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(H_PetugasLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(H_PetugasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(str_tambah_data, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(H_PetugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txt_show_mesg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jScrollPane1.setViewportView(H_Petugas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        Index index = new Index();
        index.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void panel_daftarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_daftarMouseEntered
        // TODO add your handling code here:
        setBackground(new Color(232,245,233));

    }//GEN-LAST:event_panel_daftarMouseEntered

    private void panel_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_daftarMouseClicked
        // TODO add your handling code here:
        setBackground(new Color(232,245,233));
    }//GEN-LAST:event_panel_daftarMouseClicked

    private void hover_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover_daftarMouseClicked
        // TODO add your handling code here:
            Petugas_List p_list = new Petugas_List();
            p_list.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_hover_daftarMouseClicked

    private void hover_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover_tambahMouseClicked
        // TODO add your handling code here:
        Petugas pe = new Petugas();
        pe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hover_tambahMouseClicked

    private void btn_edit_petugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_petugasActionPerformed
        // TODO add your handling code here:

        try {
            if (isEmpty()){
                txt_show_mesg.setText("DATA TIDAK BOLEH KOSONG");
                txt_show_mesg.setForeground(Color.orange);
            } else {
                nama = String.valueOf(txt_nama_petugas.getText());
                kua_cabang = String.valueOf(txt_kua_cabang.getText());
                inputFoto = new FileInputStream(foto);
                nama_foto = String.valueOf(txt_nama_foto.getText());
                path_save_foto = conn.getFolder_Foto_Petugas()+"/"+nama_foto_fromDb;
                sql = "Update data_petugas set nama_petugas = '" + nama + "', "
                        + "tempat_kua = '" + kua_cabang + "' "
                        + "where id_petugas = '" + get_id_petugas + "'";
                conn.setPreStatement(conn.getConnect().prepareStatement(sql));
                conn.getPreStatement().executeUpdate();
                saveFotoPetugas();
                Clear();
                txt_show_mesg.setText("DATA BERHASIL DI UBAH");
                txt_show_mesg.setForeground(Color.white);
            }
        } catch (SQLException e) {
            txt_show_mesg.setText("GAGAL");
            txt_show_mesg.setForeground(Color.orange);
        
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_btn_edit_petugasActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        // TODO add your handling code here:
        JFileChooser cari = new JFileChooser();
        cari.showOpenDialog(null);
        foto = cari.getSelectedFile();
        nama_file = foto.getName();
        path_file = foto.getPath();
        txt_nama_foto.setText(nama_file);
        resizeImage();
    }//GEN-LAST:event_btn_uploadActionPerformed


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Petugas_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Petugas_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Petugas_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Petugas_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Petugas_Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel H_Petugas;
    private javax.swing.JButton btn_edit_petugas;
    private javax.swing.JButton btn_upload;
    private javax.swing.JLabel foto_petugas;
    private javax.swing.JLabel hover_daftar;
    private javax.swing.JLabel hover_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_daftar;
    private javax.swing.JPanel panel_foto;
    private javax.swing.JPanel panel_tambah;
    private javax.swing.JLabel str_tambah_data;
    private javax.swing.JTextField txt_kua_cabang;
    private javax.swing.JLabel txt_nama_foto;
    private javax.swing.JTextField txt_nama_petugas;
    private javax.swing.JLabel txt_nip_petugas;
    private javax.swing.JTextField txt_show_mesg;
    // End of variables declaration//GEN-END:variables
}
